# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get Call price of a European style up-and-in barrier option
#' 
#' @param nInt number of points on single path
#' @param Strike strike price
#' @param Spot spot price at moment of pricing
#' @param Barrier barrier level
#' @param Vol volatility
#' @param Rfr risk free rate
#' @param Expiry time to maturity
#' @param nReps number of paths to simulate
#' @export
NULL

#' Get simulated paths for plotting purposes
#' 
#' @param nInt number of points on single path
#' @param Strike strike price
#' @param Spot spot price at moment of pricing
#' @param Barrier barrier level
#' @param Vol volatility
#' @param Rfr risk free rate
#' @param Expiry time to maturity
#' @param nReps number of paths to simulate
#' @export
NULL

getBarrierCallPrice <- function(nInt, Strike, Spot, Barrier, Vol, Rfr, Expiry, nReps = 1000L) {
    .Call(`_barpricer_getBarrierCallPrice`, nInt, Strike, Spot, Barrier, Vol, Rfr, Expiry, nReps)
}

getBarrierPaths <- function(nInt, Strike, Spot, Barrier, Vol, Rfr, Expiry, nReps = 1000L) {
    .Call(`_barpricer_getBarrierPaths`, nInt, Strike, Spot, Barrier, Vol, Rfr, Expiry, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_barpricer_rcpp_hello_world`)
}

